= LPN Central Yocto BSP

This is the Li-Pro.Net Central Yocto BSP Setup.

== Supported boards

In order to know the supported boards, please, see the Yocto documentation at

https://www.yoctoproject.org/documentation/

== Quick Start Guide

Once you have downloaded the source of all projects, you will have to
call:

[source,console]
$: . ./setup-environment <build directory>

After this step, you will be with everything need for build an image.

== Contributing

To contribute to the setup you should send a pull request to this GitHub
project or send the patches for review to the authors mailing address.

Issue tracker::
    https://github.com/lipro-yocto/lpn-central-bsp-base/issues

Pull requests::
    https://github.com/lipro-yocto/lpn-central-bsp-base/pulls

Source code::
    https://github.com/lipro-yocto/lpn-central-bsp-base

When creating patches, please use something like:

[source,console]
$: git format-patch -s --subject-prefix='lpn-central-bsp-base][PATCH' origin

When sending patches, please use something like:

[source,console]
$: git send-email --to rexut@users.noreply.github.com <generated patch>

To contribute to the development of this BSP and/or submit patches for
new boards please send the patches against the respective project as
informated bellow:

The following layers are included on this release:

.Included Layers 
[cols=">1s,1,3"]
|===
1.5+^.^|poky 2+|base build system and metadata
       |Path        |`sources/poky`
       |GIT         |git://git.yoctoproject.org/poky
       |Project     |https://www.yoctoproject.org/tools-resources/projects/poky
       |Mailing list|https://lists.yoctoproject.org/listinfo/yocto
1.5+^.^|meta-openembedded 2+|collection of OpenEmbedded extra packages and features
       |Path        |`sources/meta-openembedded`
       |GIT         |git://github.com/openembedded/meta-openembedded.git +
                     git://git.openembedded.org/meta-openembedded
       |Project     |https://github.com/openembedded/meta-openembedded +
                     http://git.openembedded.org/meta-openembedded
       |Mailing list|http://lists.openembedded.org/mailman/listinfo/openembedded-devel +
                     NOTE: Use [meta-oe] in subject to easy the processing
1.5+^.^|meta-qt5 2+|support for Qt5 extra packages and features
       |Path        |`sources/meta-qt5`
       |GIT         |git://github.com/meta-qt5/meta-qt5.git
       |Project     |https://github.com/meta-qt5/meta-qt5
       |Mailing list|http://lists.openembedded.org/mailman/listinfo/openembedded-devel +
                     NOTE: Use [meta-qt5] in subject to easy the processing
|===
